-- Valor total das vendas e dos fretes por produto e ordem de venda

SELECT
    DET.PRODUTOID,
	DPROD.DESCRICAO,
	DET.CUPOMID,
    SUM(DET.VALOR) AS TOTAL_VENDAS,
	SUM(CAB.VALORFRETE) AS TOTAL_FRETE
FROM FAT_DETALHES DET
INNER JOIN FAT_CABECALHO CAB ON CAB.CUPOMID = DET.CUPOMID
INNER JOIN VW_DIM_PRODUTO DPROD ON DPROD.PRODUTOID = DET.PRODUTOID
GROUP BY DET.PRODUTOID, DET.CUPOMID, DPROD.DESCRICAO 
ORDER BY DET.CUPOMID, DET.PRODUTOID