-- Objetivo: Lucro dos meses
-- 1. Calculando valor liquido (VALOR - DESCONTO = VL_LIQUIDO)
-- 2. Calculando lucro (VL_LIQUIDO - CUSTO = LUCRO)
-- Para fins de validacao optei por deixar as colunas ultilizadas para compor valor do lucro

SELECT
	YEAR(FCAB.DATA) AS ANO,
    MONTH(FCAB.DATA) AS MES,
	SUM(FDET.VALOR) AS VALOR_TOTAL,
	SUM(FDET.DESCONTO) AS TOTAL_DESCONTO,
	SUM(FDET.VALOR - FDET.DESCONTO) AS VL_LIQUIDO,
	SUM(FDET.CUSTO) AS CUSTO_TOTAL,
	SUM((FDET.VALOR - FDET.DESCONTO) - FDET.CUSTO) AS LUCRO
FROM FAT_DETALHES FDET
INNER JOIN FAT_CABECALHO FCAB ON FCAB.CUPOMID = FDET.CUPOMID
GROUP BY YEAR(DATA), MONTH(DATA)
ORDER BY YEAR(FCAB.DATA) DESC, MONTH(FCAB.DATA)