-- Venda por cliente, cidade do cliente e estado

SELECT
    FCAB.CLIENTEID,
    DCL.CLIENTE,
    DCL.CIDADE,
    'SEM CADASTRO' AS ESTADO,
    SUM(FDET.VALOR) AS TOTAL_VENDA
FROM FAT_CABECALHO FCAB
INNER JOIN FAT_DETALHES FDET ON FDET.CUPOMID = FCAB.CUPOMID
INNER JOIN DIM_CLIENTES DCL ON DCL.CLIENTEID = FCAB.CLIENTEID
GROUP BY FCAB.CLIENTEID, DCL.CLIENTE, DCL.CIDADE
ORDER BY TOTAL_VENDA DESC