--Criando View da tabela Produto/Categoria

CREATE VIEW VW_DIM_PRODUTO AS
SELECT
    TRIM(UPPER(PROD.PRODUTOID)) AS PRODUTOID,
    TRIM(UPPER(PROD.PRODUTO)) AS PRODUTO,
    TRIM(UPPER(CAT.DESCRICAO)) AS DESCRICAO,
    TRIM(UPPER(PROD.CATEGORIAID)) AS CATEGORIAID,
    TRIM(UPPER(CAT.CATEGORIA)) AS CATEGORIA
FROM DPRODUTOS AS PROD
INNER JOIN DCATEGORIA AS CAT ON PROD.CATEGORIAID = CAT.CATEGORIAID;