--Criando View Tabela FAT_VENDAS

CREATE VIEW VW_FAT_VENDAS AS
SELECT
    FDET.CUPOMID,
	FDET.PRODUTOID,
	FDET.QUANTIDADE AS QTD,
	FDET.VALOR,
	FDET.DESCONTO,
	FDET.CUSTO,
	FDET.VALORLIQUIDO,
	FCAB.DATA,
	FCAB.CLIENTEID,
	FCAB.FUNCIONARIOID,
	FCAB.VALORFRETE,
	FCAB.EMPRESAFRETE,
	FCAB.DATAENTREGA
FROM FAT_DETALHES AS FDET
INNER JOIN FAT_CABECALHO FCAB ON FCAB.CUPOMID = FDET.CUPOMID 