-- Venda por produto

SELECT
    FD.PRODUTOID,
    VWPD.PRODUTO AS PRODUTO,
    SUM(FD.VALOR) AS TOTAL_VENDAS
FROM FAT_DETALHES FD
INNER JOIN VW_DIM_PRODUTO VWPD ON VWPD.PRODUTOID = FD.PRODUTOID
GROUP BY FD.PRODUTOID, VWPD.PRODUTO
ORDER BY TOTAL_VENDAS DESC;