-- Media de produtos vendidos

SELECT
    FDET.PRODUTOID,
	VWPD.PRODUTO,
    AVG(FDET.QUANTIDADE) AS MEDIA_QTD_VENDA
FROM FAT_DETALHES FDET
INNER JOIN VW_DIM_PRODUTO VWPD ON VWPD.PRODUTOID = FDET.PRODUTOID
GROUP BY FDET.PRODUTOID, VWPD.PRODUTO
ORDER BY MEDIA_QTD_VENDA DESC